---
- name: "Arch | Install yay Dependencies"
  become: true
  community.general.pacman:
    name:
      - git
      - base-devel
    state: latest
    update_cache: true

- name: "Arch | Create aur_builder User"
  become: true
  ansible.builtin.user:
    name: aur_builder
    create_home: yes
    group: wheel

- name: "Arch | Allow aur_builder to run pacman without password"
  become: true
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/11-install-aur_builder
    line: "aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman"
    create: yes
    mode: "0644"
    validate: 'visudo -cf %s'

- name: "Arch | Install yay"
  become: true
  become_user: aur_builder
  kewlfft.aur.aur:
    name: yay
    use: makepkg
    state: present
