---
- name: "Hyprland | Arch | Install Hyprland Packages and Dependencies"
  become: true
  community.general.pacman:
    name:
      - hyprland
      - kitty
      - dolphin
      - waybar
      - rofi-wayland
      - swaync
      - pipewire
      - wireplumber
      - xdg-desktop-portal-hyprland
      - xdg-desktop-portal-gtk
      - hyprpolkitagent
      - qt5-wayland
      - qt6-wayland
      - nwg-look
      - qt5ct
      - qt6ct
      - hypridle
      - hyprlock
      - brightnessctl
      - greetd
      - greetd-regreet
      - ttf-roboto-mono-nerd
      - hyprpaper
      - hyprcursor
      - nm-connection-editor
    state: latest
    update_cache: true

- name: "Hyprland | Arch | Install AUR Packages"
  become: true
  become_user: "{{ packages.arch.aur.user }}"
  kewlfft.aur.aur:
    use: "{{ packages.arch.aur.executable }}"
    extra_args: "/var/cache/{{ packages.arch.aur.executable }}"
    name: 
      - rofi-power-menu
  when: packages.arch.aur.enabled

- name: "Hyprland | Arch | Install Cursors"
  ansible.builtin.unarchive:
    src: "https://github.com/catppuccin/cursors/releases/download/v2.0.0/catppuccin-mocha-dark-cursors.zip"
    remote_src: true
    dest: "{{ ansible_user_dir }}/.local/share/icons"
    mode: "0755"

