---
- name: "Hyprland | Fedora | Install Hyprland Packages and Dependencies"
  become: true
  ansible.builtin.dnf5:
    name: 
      - hyprland
      - dolphin
      - kitty
      - waybar
      - wofi
    state: latest

- name: "SwayNotificationCenter | Fedora | Check SwayNotificationCenter Repo"
  ansible.builtin.command:
    cmd: "dnf copr list"
  changed_when: false
  register: copr_repositories

- name: "SwayNotificatinoCenter | Fedora | Enable SwayNotificationCenter Repo"
  become: true
  ansible.builtin.command:
    cmd: "dnf copr enable erikreider/SwayNotificationCenter -y"
  when: "'SwayNotificationCenter' not in copr_repositories.stdout"
  changed_when: true

- name: "SwayNotificationCenter | Fedora | Install SwayNotificationCenter"
  become: true
  ansible.builtin.dnf5:
    name:
      - SwayNotificationCenter
    state: latest
