---
- name: "Hyprland | Fedora | Install Hyprland Packages and Dependencies"
  become: true
  ansible.builtin.dnf5:
    name: 
      - hyprland
      - dolphin
      - kitty
      - sddm
      - waybar
      - wofi
    state: latest

- name: "Hyprland | Fedora | Get Current systemd Default"
  ansible.builtin.command: 
    cmd: "systemctl get-default"
  changed_when: false
  register: systemd_default

- name: "Hyprland | Fedora | Set systemd Default to graphical target"
  become: true
  ansible.builtin.command:
    cmd: "systemctl set-default graphical.target"
  when: "'graphical' not in systemd_default.stdout"
  changed_when: true

- name: "SwayNotificationCenter | Fedora | Check SwayNotificationCenter Repo"
  ansible.builtin.command:
    cmd: "dnf copr list"
  changed_when: false
  register: copr_repositories

- name: "SwayNotificatinoCenter | Fedora | Enable SwayNotificationCenter Repo"
  become: true
  ansible.builtin.command:
    cmd: "dnf copr enable erikreider/SwayNotificationCenter -y"
  when: "'SwayNotificationCenter' not in copr_repositories.stdout"
  changed_when: true

- name: "SwayNotificationCenter | Fedora | Install SwayNotificationCenter"
  become: true
  ansible.builtin.dnf5:
    name:
      - SwayNotificationCenter
    state: latest
