---
- name: "Hyprland | Checking for Available Config: {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution }}.yml"
  register: distribution_config

- name: "Hyprland | Run Tasks: {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yml"
  when: distribution_config.stat.exists

- name: "Hyprland | Get Current systemd Default"
  ansible.builtin.command: 
    cmd: "systemctl get-default"
  changed_when: false
  register: systemd_default

- name: "Hyprland | Set systemd Default to graphical target"
  become: true
  ansible.builtin.command:
    cmd: "systemctl set-default graphical.target"
  when: "'graphical' not in systemd_default.stdout"
  changed_when: true

- name: "Hyprland | Remove Old Configs"
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.config/hypr"
    state: absent

- name: "Hyprland | Create Config Directory"
  ansible.builtin.file:
    mode: "0755"
    path: "{{ ansible_user_dir }}/.config/hypr"
    state: directory

- name: "Hyprland | Hyprland Config Link"
  ansible.builtin.file:
    src: "{{ role_path }}/files/hypr"
    dest: "{{ ansible_user_dir }}/.config/hypr"
    state: link
    force: true

- name: "Waybar | Remove Old Configs"
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.config/waybar"
    state: absent

- name: "Waybar | Create Config Directory"
  ansible.builtin.file:
    mode: "0755"
    path: "{{ ansible_user_dir }}/.config/waybar"
    state: directory

- name: "Waybar | Waybar Config Link"
  ansible.builtin.file:
    src: "{{ role_path }}/files/waybar"
    dest: "{{ ansible_user_dir }}/.config/waybar"
    state: link
    force: true

 

