---
- name: Dotfiles Config
  hosts: localhost
  connection: local

  pre_tasks:
    - name: Detect WSL
      ansible.builtin.import_tasks: pre_tasks/detect_wsl.yml
      tags:
        - always
    
    - name: Detect WSL
      ansible.builtin.debug:
        var: ansible_host_is_wsl
      tags: 
        - always

    #- name: Detect Host User
      #  when: ansible_host_is_wsl
      #ansible.builtin.import_tasks: pre_tasks/whoami_wsl.yml
      #tags:
        #  - always

    - name: Detect Host User
      when: not ansible_host_is_wsl
      ansible.builtin.import_tasks: pre_tasks/whoami.yml
      tags:
        - always

  roles:
    - tmux
