---
- name: Dotfiles Config
  hosts: localhost
  connection: local

  pre_tasks:
    - name: Detect WSL
      ansible.builtin.import_tasks: pre_tasks/detect_wsl.yml
      tags:
        - always

    - name: Detect WSL
      ansible.builtin.debug:
        var: ansible_host_is_wsl
      tags:
        - always

  roles:
    - tmux
