---
- name: "Custom | Arch | Install Custom Packages"
  become: true
  community.general.pacman:
    name: "{{ item.package }}"
    state: latest
    update_cache: true
  loop_control:
    label: "{{ item.package }}"
  loop: "{{ packages.arch.official }}"

- name: "Custom | Arch | Install Custom AUR Packages"
  community.general.pacman:
    name: "{{ item.package }}"
    state: latest
    update_cache: true
    executable: "{{ packages.arch.aur.executable }}"
    extra_args: "--builddir /var/cache/{{ packages.arch.aur.executable }}"
  loop_control:
    label: "{{ item.package }}"
  loop: "{{ packages.arch.aur.packages }}"
  when: "packages.arch.aur.enabled == true"
