---
- name: "Custom | Arch | Install Custom Packages"
  become: true
  community.general.pacman:
    name: "{{ item.package }}"
    state: latest
    update_cache: true
  loop_control:
    label: "{{ item.package }}"
  loop: "{{ packages.arch.official }}"

- name: "Custom | Arch | Install Custom AUR Packages"
  become: true
  become_user: "{{ packages.arch.aur.user }}" 
  kewlfft.aur.aur:
    use: "{{ packages.arch.aur.executable }}"
    extra_args: "--builddir /var/cache/{{ packages.arch.aur.executable }}"
    name: "{{ item.package }}"
    state: latest
    update_cache: true
  loop_control:
    label: "{{ item.package }}"
  loop: "{{ packages.arch.aur.packages }}"
  when: packages.arch.aur.enabled

- name: "Custom | Arch | Install Custom Flatpaks"
  become: true
  community.general.flatpak:
    name: "{{ item.package }}"
    state: latest
  loop_control:
    label: "{{ item.package }}"
  loop: "{{ packages.flatpak }}"


