---
- name: "Arch | Update Packages" 
  become: true
  community.general.pacman:
    update_cache: true
    upgrade: true

- name: "Arch | System Setup"
  become: true
  community.general.pacman:
    name:
      - curl
      - fastfetch
      - file
      - firewalld
      - gzip
      - jq
      - man-db
      - man-pages
      - openssh
      - tar
      - unzip
      - wget
    state: latest
