---
- name: System Setup for Fedora
  become: true
  ansible.builtin.dnf5:
    name:
      - curl
      - fastfetch
      - file
      - gcc
      - gzip
      - helm
      - jq
      - man-db
      - man-pages
      - neovim
      - nodejs
      - opentofu
      - ripgrep
      - tar
      - tmux
      - trivy
      - unzip
      - wget
      - zsh
    state: latest
