---
- name: "Fedora | Update Packages"
  become: true
  ansible.builtin.dnf5:
    name: "*"
    state: latest

- name: "Fedora | System Setup"
  become: true
  ansible.builtin.dnf5:
    name:
      - curl
      - fastfetch
      - file
      - gzip
      - jq
      - man-db
      - man-pages
      - openssh
      - tar
      - unzip
      - wget
    state: latest
